version: "3"

services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    volumes:
      - ./logs:/logs
      - ./notebook:/notebook
    environment:
      - ZEPPELIN_NOTEBOOK_DIR='/notebook'
      - ZEPPELIN_LOG_DIR='/logs'
    ports:
      - "8080:8080"
